# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Code Happens
email: ytp@yadayadacreative.com
description: > # this means to ignore newlines until "baseurl:"
  HackReactor Student | Programmer | Traveler | Little Sister | Geographically Confused | Dog Parent
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yctercero.github.io" # the base hostname & protocol for your site
github_username:  yctercero

# Build settings
markdown: kramdown

gems: [jekyll-paginate]

excerpt_separator: "<!--excerpt-->"